name: Unit Test

on: [pushed]

concurrency:
  group: ${{ github.refs }}
  cancel-in-progress: true

jobs:
  run-tests:
    name: 🧪 Run Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        run: |
          python test*.py

  celebrate-tests:
    name: Celebrate the success of our unit tests
    runs-on: ubuntu-lastest
    needs: [tests]
    steps:
      - name: Install figlet
        run: |
          sudo apt-get -y install figlet
          which figlet
      - name: Show celebration text
        run: figlet 'Oh wow! You did it!!! The unit tests passed!'
